#This file will deploy our apps into clusters dynmicallt
# With this appicationset config, we can add clusters and argocdd deploys to these clusters autmatically
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: boutique-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernates.default.svc
        path: k8s/base
      # This is an example of how to add a second cluster to the applicationset
      # - cluster: us-east-2
      #   url: https://us-east-2.eks.amazonaws.com
      #   path: k8s/base
  template:
    metadata:
      name: '{{cluster}}-boutique-application'
    spec:
      project: boutique-project
      source:
        repoURL: https://github.com/kennethchinedu/NovaOps-Platform-Project #This is a public repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - SkipDryRunOnMissingResource=true 