

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: inginx-system-utils 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-utils
  rules:
  - host:   aaf79befcefde4c268fb191f55d08213-385547497.us-east-1.elb.amazonaws.com  #  load balancer url 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

                  






# adding below annotation solved the problem for me

# alb.ingress.kubernetes.io/target-type: ip
# full ingress looks like this

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /*
#             pathType: Prefix
#             backend:
#               service:
#                 name: my-servilsce
#                 port:

#                   number: 80