# We will hardcode ip addresses for the load balancer temporarily for now and make it public
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minikube-pool
  namespace: metallb-system
spec:
  addresses:
  - 102.91.72.35-102.91.72.120
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: minikube-lb
  namespace: metallb-system

